# Name: Ethan Wong
# Email: ethanwong@g.ucla.edu
# ID: 305319001

.SILENT: 
dist:
	tar -zvcf lab4a-305319001.tar.gz my_beaglebone.jpg  build_run.png git.png connected.png copy.png Makefile README

clean:
	rm -rf *~ *.tar.gz