# NAME: Ethan Wong
# EMAIL: ethanwong@g.ucla.edu
# ID: 305319001

CC = gcc

default:
	$(CC) -o  lab1a -g -Wall -Wextra lab1a.c

clean:
	rm -rf lab1a *.tar.gz

dist:
	tar -cvzf lab1a-305319001.tar.gz lab1a.c Makefile README 