# NAME: Ethan Wong
# EMAIL: ethanwong@g.ucla.edu
# ID: 305319001

build:
  gcc -o -g -Wall -Wextra -pthread lab2_add lab2_add.c

graphs:
  ./lab2_add.gp

clean:
  rm -rf lab2_add *.o *.tar.gz

dist: 
  